# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  username: postgres
  password: 2016
  database: trackmymoney_development

production:
  <<: *default
  database: trackmymoney_production
  username: trackmymoney
  password: <%= ENV['MY_MONEY_DATABASE_PASSWORD'] %>
